[tool.uv.workspace]
members = ["contact_lookup", "contact_multiple_surfaces", "orchestrator", "restaurant_finder", "rizzcharts"]

[tool.uv.sources]
a2ui = { path = "../../../a2a_agents/python/a2ui_extension" }

